/**
 * Catálogo genérico de serie (CATALOGO_Y_ERGONOMIA §2). Medidas en cm,
 * ancho × fondo × alto. Son valores por defecto: el usuario las cambia.
 */
import type { z } from 'zod';
import type { Template } from '../model/schemas';

export type TemplateId = z.infer<typeof Template>;

export interface GenericItem {
  key: string;
  group: 'salon' | 'comedor' | 'dormitorio' | 'cocina' | 'bano' | 'varios';
  name: string;
  /** Categoría del mueble en el proyecto. */
  category: string;
  template: TemplateId;
  w: number;
  d: number;
  h: number;
  color: string;
  /** Huella con partes extendidas (chaise, asientos deslizantes…). */
  extended?: { w: number; d: number };
  params?: Record<string, number | string>;
}

const SOFA = '#b9ad97';
const WOOD = '#c9a77c';
const WHITE = '#ece8e0';
const DARK = '#4a5658';
const TEXTILE = '#d9cbb3';

export const GENERIC_CATALOG: readonly GenericItem[] = [
  // Salón
  {
    key: 'sofa2',
    group: 'salon',
    name: 'Sofá 2 plazas',
    category: 'sofa',
    template: 'sofa',
    w: 160,
    d: 90,
    h: 85,
    color: SOFA,
  },
  {
    key: 'sofa3',
    group: 'salon',
    name: 'Sofá 3 plazas',
    category: 'sofa',
    template: 'sofa',
    w: 210,
    d: 92,
    h: 85,
    color: SOFA,
  },
  {
    key: 'sofa3xl',
    group: 'salon',
    name: 'Sofá 3 plazas XL',
    category: 'sofa',
    template: 'sofa',
    w: 235,
    d: 95,
    h: 90,
    color: SOFA,
  },
  {
    key: 'chaise',
    group: 'salon',
    name: 'Sofá chaise longue',
    category: 'sofa',
    template: 'sofa_chaise',
    w: 240,
    d: 90,
    h: 88,
    color: SOFA,
    extended: { w: 240, d: 155 },
    params: { chaiseSide: 'izq', reversible: 1 },
  },
  {
    key: 'deslizante',
    group: 'salon',
    name: 'Sofá asientos deslizantes',
    category: 'sofa',
    template: 'sofa_deslizante',
    w: 230,
    d: 95,
    h: 100,
    color: SOFA,
    extended: { w: 230, d: 155 },
    params: { slideExtra: 60 },
  },
  {
    key: 'rinconera',
    group: 'salon',
    name: 'Rinconera',
    category: 'sofa',
    template: 'rinconera',
    w: 260,
    d: 200,
    h: 85,
    color: SOFA,
  },
  {
    key: 'sillon',
    group: 'salon',
    name: 'Sillón',
    category: 'sofa',
    template: 'sofa',
    w: 80,
    d: 85,
    h: 95,
    color: SOFA,
  },
  {
    key: 'puff',
    group: 'salon',
    name: 'Puff',
    category: 'puff',
    template: 'caja',
    w: 50,
    d: 50,
    h: 42,
    color: TEXTILE,
  },
  {
    key: 'mesacentro',
    group: 'salon',
    name: 'Mesa de centro',
    category: 'mesa',
    template: 'mesa',
    w: 110,
    d: 60,
    h: 42,
    color: WOOD,
  },
  {
    key: 'muebletv',
    group: 'salon',
    name: 'Mueble TV',
    category: 'mueble_bajo',
    template: 'mueble_bajo',
    w: 160,
    d: 40,
    h: 50,
    color: WHITE,
  },
  {
    key: 'tv55',
    group: 'salon',
    name: 'TV 55"',
    category: 'tv',
    template: 'tv',
    w: 123,
    d: 8,
    h: 71,
    color: DARK,
    params: { diagonalInch: 55 },
  },
  {
    key: 'tv65',
    group: 'salon',
    name: 'TV 65"',
    category: 'tv',
    template: 'tv',
    w: 145,
    d: 8,
    h: 83,
    color: DARK,
    params: { diagonalInch: 65 },
  },
  {
    key: 'estanteria',
    group: 'salon',
    name: 'Estantería',
    category: 'estanteria',
    template: 'estanteria',
    w: 80,
    d: 35,
    h: 180,
    color: WOOD,
  },
  {
    key: 'alfombra',
    group: 'salon',
    name: 'Alfombra 160 × 230',
    category: 'alfombra',
    template: 'alfombra',
    w: 230,
    d: 160,
    h: 1,
    color: TEXTILE,
  },
  {
    key: 'alfombra2',
    group: 'salon',
    name: 'Alfombra 200 × 290',
    category: 'alfombra',
    template: 'alfombra',
    w: 290,
    d: 200,
    h: 1,
    color: TEXTILE,
  },
  // Comedor
  {
    key: 'mesa4',
    group: 'comedor',
    name: 'Mesa comedor 4 (120 × 80)',
    category: 'mesa',
    template: 'mesa',
    w: 120,
    d: 80,
    h: 75,
    color: WOOD,
  },
  {
    key: 'mesa6',
    group: 'comedor',
    name: 'Mesa comedor 6 (160 × 90)',
    category: 'mesa',
    template: 'mesa',
    w: 160,
    d: 90,
    h: 75,
    color: WOOD,
  },
  {
    key: 'mesaext',
    group: 'comedor',
    name: 'Mesa extensible 140 (190)',
    category: 'mesa',
    template: 'mesa',
    w: 140,
    d: 90,
    h: 75,
    color: WOOD,
    extended: { w: 190, d: 90 },
  },
  {
    key: 'mesaredonda',
    group: 'comedor',
    name: 'Mesa redonda Ø105',
    category: 'mesa',
    template: 'mesa',
    w: 105,
    d: 105,
    h: 75,
    color: WOOD,
    params: { shape: 'redonda' },
  },
  {
    key: 'silla',
    group: 'comedor',
    name: 'Silla',
    category: 'silla',
    template: 'silla',
    w: 45,
    d: 52,
    h: 85,
    color: WHITE,
  },
  {
    key: 'aparador',
    group: 'comedor',
    name: 'Aparador',
    category: 'mueble_bajo',
    template: 'mueble_bajo',
    w: 160,
    d: 45,
    h: 80,
    color: WOOD,
  },
  // Dormitorio
  {
    key: 'cama90',
    group: 'dormitorio',
    name: 'Cama individual 90',
    category: 'cama',
    template: 'cama',
    w: 100,
    d: 205,
    h: 50,
    color: TEXTILE,
  },
  {
    key: 'cama135',
    group: 'dormitorio',
    name: 'Cama 135',
    category: 'cama',
    template: 'cama',
    w: 145,
    d: 205,
    h: 50,
    color: TEXTILE,
  },
  {
    key: 'cama150',
    group: 'dormitorio',
    name: 'Cama 150',
    category: 'cama',
    template: 'cama',
    w: 160,
    d: 210,
    h: 50,
    color: TEXTILE,
  },
  {
    key: 'cama160',
    group: 'dormitorio',
    name: 'Cama 160',
    category: 'cama',
    template: 'cama',
    w: 170,
    d: 215,
    h: 50,
    color: TEXTILE,
  },
  {
    key: 'cama180',
    group: 'dormitorio',
    name: 'Cama 180',
    category: 'cama',
    template: 'cama',
    w: 190,
    d: 215,
    h: 50,
    color: TEXTILE,
  },
  {
    key: 'mesita',
    group: 'dormitorio',
    name: 'Mesita de noche',
    category: 'mueble_bajo',
    template: 'mueble_bajo',
    w: 45,
    d: 40,
    h: 50,
    color: WOOD,
  },
  {
    key: 'comoda',
    group: 'dormitorio',
    name: 'Cómoda',
    category: 'mueble_bajo',
    template: 'mueble_bajo',
    w: 100,
    d: 45,
    h: 80,
    color: WOOD,
  },
  {
    key: 'armario2',
    group: 'dormitorio',
    name: 'Armario 2 puertas',
    category: 'armario',
    template: 'armario',
    w: 100,
    d: 60,
    h: 200,
    color: WHITE,
    params: { doors: 2, doorType: 'abatible' },
  },
  {
    key: 'armario3',
    group: 'dormitorio',
    name: 'Armario 3 puertas',
    category: 'armario',
    template: 'armario',
    w: 150,
    d: 60,
    h: 220,
    color: WHITE,
    params: { doors: 3, doorType: 'abatible' },
  },
  {
    key: 'armariocorr',
    group: 'dormitorio',
    name: 'Armario corredera',
    category: 'armario',
    template: 'armario',
    w: 200,
    d: 65,
    h: 230,
    color: WHITE,
    params: { doors: 2, doorType: 'corredera' },
  },
  {
    key: 'escritorio',
    group: 'dormitorio',
    name: 'Escritorio',
    category: 'mesa',
    template: 'mesa',
    w: 120,
    d: 60,
    h: 75,
    color: WHITE,
  },
  {
    key: 'sillaescr',
    group: 'dormitorio',
    name: 'Silla de escritorio',
    category: 'silla',
    template: 'silla',
    w: 60,
    d: 60,
    h: 100,
    color: DARK,
  },
  // Cocina y lavado
  {
    key: 'combi',
    group: 'cocina',
    name: 'Frigorífico combi',
    category: 'electrodomestico',
    template: 'electrodomestico',
    w: 60,
    d: 65,
    h: 190,
    color: WHITE,
  },
  {
    key: 'americano',
    group: 'cocina',
    name: 'Frigorífico americano',
    category: 'electrodomestico',
    template: 'electrodomestico',
    w: 91,
    d: 72,
    h: 178,
    color: WHITE,
  },
  {
    key: 'lavadora',
    group: 'cocina',
    name: 'Lavadora',
    category: 'electrodomestico',
    template: 'electrodomestico',
    w: 60,
    d: 60,
    h: 85,
    color: WHITE,
  },
  {
    key: 'secadora',
    group: 'cocina',
    name: 'Secadora',
    category: 'electrodomestico',
    template: 'electrodomestico',
    w: 60,
    d: 60,
    h: 85,
    color: WHITE,
  },
  {
    key: 'lavavajillas',
    group: 'cocina',
    name: 'Lavavajillas',
    category: 'electrodomestico',
    template: 'electrodomestico',
    w: 60,
    d: 60,
    h: 82,
    color: WHITE,
  },
  {
    key: 'bajo60',
    group: 'cocina',
    name: 'Módulo bajo 60',
    category: 'mueble_bajo',
    template: 'mueble_bajo',
    w: 60,
    d: 60,
    h: 85,
    color: WHITE,
  },
  {
    key: 'alto60',
    group: 'cocina',
    name: 'Módulo alto 60',
    category: 'mueble_alto',
    template: 'mueble_bajo',
    w: 60,
    d: 35,
    h: 70,
    color: WHITE,
  },
  // Baño
  {
    key: 'inodoro',
    group: 'bano',
    name: 'Inodoro',
    category: 'sanitario',
    template: 'caja',
    w: 37,
    d: 65,
    h: 80,
    color: '#ffffff',
  },
  {
    key: 'lavabo',
    group: 'bano',
    name: 'Lavabo con mueble',
    category: 'sanitario',
    template: 'mueble_bajo',
    w: 70,
    d: 45,
    h: 85,
    color: '#ffffff',
  },
  {
    key: 'ducha',
    group: 'bano',
    name: 'Plato de ducha 80 × 120',
    category: 'sanitario',
    template: 'caja',
    w: 120,
    d: 80,
    h: 5,
    color: '#ffffff',
  },
  {
    key: 'banera',
    group: 'bano',
    name: 'Bañera 170',
    category: 'sanitario',
    template: 'caja',
    w: 170,
    d: 75,
    h: 55,
    color: '#ffffff',
  },
  // Mascotas y varios
  {
    key: 'perroM',
    group: 'varios',
    name: 'Cama de perro M',
    category: 'mascota',
    template: 'caja',
    w: 80,
    d: 60,
    h: 20,
    color: TEXTILE,
  },
  {
    key: 'perroL',
    group: 'varios',
    name: 'Cama de perro L',
    category: 'mascota',
    template: 'caja',
    w: 100,
    d: 75,
    h: 25,
    color: TEXTILE,
  },
  {
    key: 'comedero',
    group: 'varios',
    name: 'Comedero',
    category: 'mascota',
    template: 'caja',
    w: 40,
    d: 25,
    h: 8,
    color: DARK,
  },
  {
    key: 'arbol',
    group: 'varios',
    name: 'Árbol de Navidad 180',
    category: 'arbol',
    template: 'arbol',
    w: 75,
    d: 75,
    h: 180,
    color: '#4f7a52',
    params: { radius: 37 },
  },
  {
    key: 'planta',
    group: 'varios',
    name: 'Cubo con planta',
    category: 'planta',
    template: 'planta',
    w: 40,
    d: 30,
    h: 40,
    color: WOOD,
  },
];

export const GROUP_ORDER: readonly GenericItem['group'][] = [
  'salon',
  'comedor',
  'dormitorio',
  'cocina',
  'bano',
  'varios',
];

/** Búsqueda sin tildes ni mayúsculas. */
/** Palabras habituales que no aparecen en el nombre del catálogo. */
const SYNONYMS: Record<string, string> = {
  nevera: 'frigorifico',
  frigo: 'frigorifico',
  tele: 'tv',
  television: 'tv',
  televisor: 'tv',
  wc: 'inodoro',
  vater: 'inodoro',
  libreria: 'estanteria',
  mesilla: 'mesita',
  butaca: 'sillon',
};

export function searchCatalog(query: string, items: readonly GenericItem[] = GENERIC_CATALOG) {
  const norm = (s: string) =>
    s
      .normalize('NFD')
      .replace(/\p{Diacritic}/gu, '')
      .toLowerCase();
  const q = norm(query.trim());
  if (!q) return [...items];
  const words = q.split(/\s+/).map((w) => SYNONYMS[w] ?? w);
  return items.filter((i) => {
    const text = norm(`${i.name} ${i.category} ${i.group}`);
    return words.every((w) => text.includes(w));
  });
}
